name: Trivy Image Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Build & Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            # --build-arg STRAPI_URL=https://api.example.com \ # Uncomment to set the Strapi Server URL
            -t mystrapiapp:latest \ # Replace with your image name
            -f Dockerfile .

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: strapi-app:${{ github.sha }}
          format: 'table'          # optional: table, json, etc.
          exit-code: '1'           # non-zero if any vuln found
          vuln-type: 'os,library'  # scan OS packages & app deps